### ISSUE TITLE
How to depend on wpilibNewCommands-cpp?

### ISSUE THREAD

**Issue by mjansen4857** [wpilibsuite/vendor-template#10]
The vendor template includes a dependency on wpilibNewCommands for java by default, but does not include this dependency for c++. I can't seem to figure out how to include this dependency myself as I am not too familiar with using gradle or the wpilib gradle plugins, and I can't find any documentation on depending on it without using the new commands vendordep. How would I go about including this dependency in the template?

**Comment by ThadHouse** [comment]
Supporting vendor deps at all in the vendor template isn't really supported. Theres ways, but they require digging in, and using interfaces that we do occasionally break. Thats why they're not documented. I can look into an example how to do that, but in general the vendor template was made for hardware drivers and not high level libraries.

**Comment by mjansen4857** [comment]
If its too "hacky" to implement nicely its no big deal. Just wondering if there was some sort of C++ equivalent of `implementation 'edu.wpi.first.wpilibNewCommands:wpilibNewCommands-java:2023.+'`.

Also, am I correct in assuming that if the C++ version could depend on new commands this would cause issues including my vendordep in a robot code project that doesn't also use the new commands library?

**Comment by sciencewhiz** [comment]
> The vendor template includes a dependency on wpilibNewCommands for java by default,

Are you sure about that? The line you quote isn't in the template.

**Comment by mjansen4857** [comment]
You’re right, my bad. I totally forgot adding that myself I guess.

**Comment by rbiliff** [comment]
@mjansen4857 I was able to fumble my way through figuring it out for our WIP vendordep. You can pretty much add into your `config.gradle`:
```gradle
nativeUtils.wpi.addVendorDeps()
nativeUtils.wpi.getVendorDeps().loadAll()
nativeUtils.wpi.getVendorDeps().getNativeVendor().initializeNativeDependencies()
nativeUtils.wpi.getVendorDeps().addVendorReposToMaven(false)

model {
    components {
        all {
            nativeUtils.useAllPlatforms(it)
        }
    }
    binaries {
        withType(NativeBinarySpec).all {
            nativeUtils.usePlatformArguments(it)
            nativeUtils.wpi.getVendorDeps().getNativeVendor().cpp(it)
        }
    }
}
``` 

Main thing is that the actual robot project should be at the same version of the vendordeps as your library otherwise you'll end up with linking errors (if there's a breaking change atleast) which'll be very confusing for teams to debug on their own.
If you want, here's also a link for our use of it if you want to see the black magic for it: https://github.com/LASER3284/MotorMotion/blob/2023/config.gradle#L23
I'll say it would be nice if the vendor template/vendordeps more actively supported using other vendordeps in them so teams can easily install libraries and such 👍

**Comment by mjansen4857** [comment]
That worked! You're awesome, thank you!

Definitely second the idea of official support of vendordeps within vendordeps. Probably a little re-work of the concept of "vendordeps" to not only have hardware vendors in mind would make sense. A lot of teams have their own libraries of code they use every year. Being able to maintain this as a "vendordep" would make using it and sharing it with other teams easier.

**Comment by ThadHouse** [comment]
Part of the reason we've avoided doing that in the past is since this infrastructure is at a lower level then gradlerio, it changes much more often. Year over year this setup generally requires pretty major updates in order to work. Pretty much all vendors have gotten used to manually doing that, and they all pretty much have direct contact with me in order to do those updates each year. We don't have a built in updater, because these are usually much more custom then a robot project, where an updater wouldn't make sense.

Currently as well there is no transitive support in vendor deps. adding that would be possible, but adds some complication over what we have currently, in a way that is fragile to maintain year over year. 

One final quirk is the artifacts published from here need to be sure to not take actual maven dependencies on any wpilib libraries. The default in Java is to mark the artifacts as actually depending on the wpilib libraries. However, if for some reason the vendor dep is built newer then wpilib (This actually happens more often then you think), then team code can actually break. This has happened before.

**Comment by mjansen4857** [comment]
Just out of curiosity, is there any reason why the vendordep infrastructure is at a lower level? More specifically, why not use GradleRIO to manage dependencies for a vendordep as it does for a robot project? Is it just to allow vendors to have lower-level control?

**Comment by ThadHouse** [comment]
Mostly. Vendor setups can end up being much more complicated then team code, especially since they need to generally support all languages and all platforms. For teams, they usually don’t need that big of a matrix of support. Also there’s a lot of magic in gradlerio that can occasionally interfere with what vendors need to do.
